#!/usr/bin/env bash
# Check for root user
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi
# Overwrite /etc/hosts with the required content
cat <<EOF > /etc/hosts
127.0.0.2    localhost
8.8.8.8      facebook.com
EOF
